# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f68a24fb15e1329c014bee84bedbde37807574df7281a084e62d11b419527508d42100d765d381ab5cf43228850f15a4f15b8a06a35b5a3dc14cd0f07069dde7

test:
  secret_key_base: 4d6836559e43481bc46b2ca82af9faf9611405589c772c1a23ce717c3b6d64d1656476ffd80dd9c6b5bede31cb55e14c817cd1cf2d36cdc1df5e0cb57ecabc05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
